version: '3.5'

services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: devops_traefik_api3
    restart: always
    command:
      - --providers.docker=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"

networks:
  proxy:
    name: ${PROXY_NAME:-api3}
    external: true