version: "3.9"
services:
  nuxt:
    build: .
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - app_dotnuxt:/app/.nuxt
    command: [yarn, dev]
    ports:
      - "8080:3000"
    labels:
      - "traefik.http.routers.nuxt.tls=true"
      - "traefik.http.routers.nuxt.rule=Host(`my-youtube.local`)"
volumes:
  app_node_modules:
  app_dotnuxt:

networks:
  default:
    name: api3
    external: true
